POST http://localhost:3003/students
Content-Type: application/json

{
    "name": "Edson",
    "email": "edson.junior@hotmail.com",
    "birthDate": "03/11/1995",
    "classGroup": "1"
}

###
PUT http://localhost:3003/students/class
Content-Type: application/json

{
    "id": "1645192721628",
    "classGroup": "2"
}

###
GET http://localhost:3003/students?name=Edson
Content-Type: application/json

###

POST http://localhost:3003/students/hobbies
Content-Type: application/json

{
    "userId": "1645198577254",
    "name": "Andar de bike"
}
###

POST http://localhost:3003/teachers
Content-Type: application/json

{
"classGroup": "1",
"name": "Larissa",
"email": "larisa@hotmail.com", 
"birthDate": "23/12/1995"
}













###
GET http://localhost:3003/teachers?name=larissa
Content-Type: application/json